version: '3.8'

services:
  api:
    image: golang:1.20-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "go run main.go"
    ports:
      - "8080:8080"
    depends_on:
      - db
    
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: